/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AtsResult {
  'suggestions' : Array<string>,
  'matchedKeywords' : Array<string>,
  'score' : bigint,
}
export interface EnhancedBullet {
  'improvement' : string,
  'enhanced' : string,
  'original' : string,
}
export interface ExperienceEntry {
  'duration' : string,
  'bullets' : Array<string>,
  'company' : string,
  'jobTitle' : string,
}
export interface ProjectEntry {
  'title' : string,
  'bullets' : Array<string>,
  'description' : string,
}
export interface SkillAnalysis {
  'tools' : Array<string>,
  'technical' : Array<string>,
  'categoryExplanation' : string,
  'softSkills' : Array<string>,
}
export interface _SERVICE {
  'analyzeSkills' : ActorMethod<[Array<string>], SkillAnalysis>,
  'calculateAtsScore' : ActorMethod<
    [Array<ExperienceEntry>, Array<ProjectEntry>],
    AtsResult
  >,
  'enhanceBullets' : ActorMethod<[Array<string>], Array<EnhancedBullet>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];