/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SkillAnalysis = IDL.Record({
  'tools' : IDL.Vec(IDL.Text),
  'technical' : IDL.Vec(IDL.Text),
  'categoryExplanation' : IDL.Text,
  'softSkills' : IDL.Vec(IDL.Text),
});
export const ExperienceEntry = IDL.Record({
  'duration' : IDL.Text,
  'bullets' : IDL.Vec(IDL.Text),
  'company' : IDL.Text,
  'jobTitle' : IDL.Text,
});
export const ProjectEntry = IDL.Record({
  'title' : IDL.Text,
  'bullets' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
});
export const AtsResult = IDL.Record({
  'suggestions' : IDL.Vec(IDL.Text),
  'matchedKeywords' : IDL.Vec(IDL.Text),
  'score' : IDL.Nat,
});
export const EnhancedBullet = IDL.Record({
  'improvement' : IDL.Text,
  'enhanced' : IDL.Text,
  'original' : IDL.Text,
});

export const idlService = IDL.Service({
  'analyzeSkills' : IDL.Func([IDL.Vec(IDL.Text)], [SkillAnalysis], ['query']),
  'calculateAtsScore' : IDL.Func(
      [IDL.Vec(ExperienceEntry), IDL.Vec(ProjectEntry)],
      [AtsResult],
      ['query'],
    ),
  'enhanceBullets' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Vec(EnhancedBullet)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SkillAnalysis = IDL.Record({
    'tools' : IDL.Vec(IDL.Text),
    'technical' : IDL.Vec(IDL.Text),
    'categoryExplanation' : IDL.Text,
    'softSkills' : IDL.Vec(IDL.Text),
  });
  const ExperienceEntry = IDL.Record({
    'duration' : IDL.Text,
    'bullets' : IDL.Vec(IDL.Text),
    'company' : IDL.Text,
    'jobTitle' : IDL.Text,
  });
  const ProjectEntry = IDL.Record({
    'title' : IDL.Text,
    'bullets' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
  });
  const AtsResult = IDL.Record({
    'suggestions' : IDL.Vec(IDL.Text),
    'matchedKeywords' : IDL.Vec(IDL.Text),
    'score' : IDL.Nat,
  });
  const EnhancedBullet = IDL.Record({
    'improvement' : IDL.Text,
    'enhanced' : IDL.Text,
    'original' : IDL.Text,
  });
  
  return IDL.Service({
    'analyzeSkills' : IDL.Func([IDL.Vec(IDL.Text)], [SkillAnalysis], ['query']),
    'calculateAtsScore' : IDL.Func(
        [IDL.Vec(ExperienceEntry), IDL.Vec(ProjectEntry)],
        [AtsResult],
        ['query'],
      ),
    'enhanceBullets' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Vec(EnhancedBullet)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };